runtime: java
env: flex
runtime_config:
  operating_system: windows
  runtime_version: 1.8
entrypoint: "patstools.war"
handlers:
  - url: /.*
    script: this field is required, but ignored
manual_scaling:
  instances: 1 # Adjust as needed